//
// asio.hpp
// ~~~~~~~~
//
// Copyright (c) 2003-2026 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef ASIO_HPP
#define ASIO_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
# pragma once
#endif // defined(_MSC_VER) && (_MSC_VER >= 1200)

#include <xio/any_completion_executor.h>
#include <xio/any_completion_handler.h>
#include <xio/any_io_executor.h>
#include <xio/append.h>
#include <xio/as_tuple.h>
#include <xio/associated_allocator.h>
#include <xio/associated_cancellation_slot.h>
#include <xio/associated_executor.h>
#include <xio/associated_immediate_executor.h>
#include <xio/associator.h>
#include <xio/async_result.h>
#include <xio/awaitable.h>
#include <xio/basic_datagram_socket.h>
#include <xio/basic_file.h>
#include <xio/basic_io_object.h>
#include <xio/basic_random_access_file.h>
#include <xio/basic_raw_socket.h>
#include <xio/basic_readable_pipe.h>
#include <xio/basic_seq_packet_socket.h>
#include <xio/basic_serial_port.h>
#include <xio/basic_signal_set.h>
#include <xio/basic_socket.h>
#include <xio/basic_socket_acceptor.h>
#include <xio/basic_socket_iostream.h>
#include <xio/basic_socket_streambuf.h>
#include <xio/basic_stream_file.h>
#include <xio/basic_stream_socket.h>
#include <xio/basic_streambuf.h>
#include <xio/basic_waitable_timer.h>
#include <xio/basic_writable_pipe.h>
#include <xio/bind_allocator.h>
#include <xio/bind_cancellation_slot.h>
#include <xio/bind_executor.h>
#include <xio/bind_immediate_executor.h>
#include <xio/buffer.h>
#include <xio/buffer_registration.h>
#include <xio/buffered_read_stream_fwd.h>
#include <xio/buffered_read_stream.h>
#include <xio/buffered_stream_fwd.h>
#include <xio/buffered_stream.h>
#include <xio/buffered_write_stream_fwd.h>
#include <xio/buffered_write_stream.h>
#include <xio/buffers_iterator.h>
#include <xio/cancel_after.h>
#include <xio/cancel_at.h>
#include <xio/cancellation_signal.h>
#include <xio/cancellation_state.h>
#include <xio/cancellation_type.h>
#include <xio/co_composed.h>
#include <xio/co_spawn.h>
#include <xio/completion_condition.h>
#include <xio/compose.h>
#include <xio/composed.h>
#include <xio/config.h>
#include <xio/connect.h>
#include <xio/connect_pipe.h>
#include <xio/consign.h>
#include <xio/coroutine.h>
#include <xio/defer.h>
#include <xio/deferred.h>
#include <xio/default_completion_token.h>
#include <xio/detached.h>
#include <xio/dispatch.h>
#include <xio/disposition.h>
#include <xio/error.h>
#include <xio/error_code.h>
#include <xio/execution.h>
#include <xio/execution/allocator.h>
#include <xio/execution/any_executor.h>
#include <xio/execution/blocking.h>
#include <xio/execution/blocking_adaptation.h>
#include <xio/execution/context.h>
#include <xio/execution/context_as.h>
#include <xio/execution/executor.h>
#include <xio/execution/invocable_archetype.h>
#include <xio/execution/mapping.h>
#include <xio/execution/occupancy.h>
#include <xio/execution/outstanding_work.h>
#include <xio/execution/prefer_only.h>
#include <xio/execution/relationship.h>
#include <xio/executor.h>
#include <xio/executor_work_guard.h>
#include <xio/file_base.h>
#include <xio/generic/basic_endpoint.h>
#include <xio/generic/datagram_protocol.h>
#include <xio/generic/raw_protocol.h>
#include <xio/generic/seq_packet_protocol.h>
#include <xio/generic/stream_protocol.h>
#include <xio/handler_continuation_hook.h>
#include <xio/high_resolution_timer.h>
#include <xio/immediate.h>
#include <xio/inline_executor.h>
#include <xio/inline_or_executor.h>
#include <xio/io_context.h>
#include <xio/io_context_strand.h>
#include <xio/ip/address.h>
#include <xio/ip/address_v4.h>
#include <xio/ip/address_v4_iterator.h>
#include <xio/ip/address_v4_range.h>
#include <xio/ip/address_v6.h>
#include <xio/ip/address_v6_iterator.h>
#include <xio/ip/address_v6_range.h>
#include <xio/ip/network_v4.h>
#include <xio/ip/network_v6.h>
#include <xio/ip/bad_address_cast.h>
#include <xio/ip/basic_endpoint.h>
#include <xio/ip/basic_resolver.h>
#include <xio/ip/basic_resolver_entry.h>
#include <xio/ip/basic_resolver_iterator.h>
#include <xio/ip/basic_resolver_query.h>
#include <xio/ip/host_name.h>
#include <xio/ip/icmp.h>
#include <xio/ip/multicast.h>
#include <xio/ip/resolver_base.h>
#include <xio/ip/resolver_query_base.h>
#include <xio/ip/tcp.h>
#include <xio/ip/udp.h>
#include <xio/ip/unicast.h>
#include <xio/ip/v6_only.h>
#include <xio/is_applicable_property.h>
#include <xio/is_contiguous_iterator.h>
#include <xio/is_executor.h>
#include <xio/is_read_buffered.h>
#include <xio/is_write_buffered.h>
#include <xio/local/basic_endpoint.h>
#include <xio/local/connect_pair.h>
#include <xio/local/datagram_protocol.h>
#include <xio/local/seq_packet_protocol.h>
#include <xio/local/stream_protocol.h>
#include <xio/multiple_exceptions.h>
#include <xio/packaged_task.h>
#include <xio/placeholders.h>
#include <xio/posix/basic_descriptor.h>
#include <xio/posix/basic_stream_descriptor.h>
#include <xio/posix/descriptor.h>
#include <xio/posix/descriptor_base.h>
#include <xio/posix/stream_descriptor.h>
#include <xio/post.h>
#include <xio/prefer.h>
#include <xio/prepend.h>
#include <xio/query.h>
#include <xio/random_access_file.h>
#include <xio/read.h>
#include <xio/read_at.h>
#include <xio/read_until.h>
#include <xio/readable_pipe.h>
#include <xio/recycling_allocator.h>
#include <xio/redirect_disposition.h>
#include <xio/redirect_error.h>
#include <xio/registered_buffer.h>
#include <xio/require.h>
#include <xio/require_concept.h>
#include <xio/serial_port.h>
#include <xio/serial_port_base.h>
#include <xio/signal_set.h>
#include <xio/signal_set_base.h>
#include <xio/socket_base.h>
#include <xio/static_thread_pool.h>
#include <xio/steady_timer.h>
#include <xio/strand.h>
#include <xio/stream_file.h>
#include <xio/streambuf.h>
#include <xio/system_context.h>
#include <xio/system_error.h>
#include <xio/system_executor.h>
#include <xio/system_timer.h>
#include <xio/this_coro.h>
#include <xio/thread.h>
#include <xio/thread_pool.h>
#include <xio/use_awaitable.h>
#include <xio/use_future.h>
#include <xio/uses_executor.h>
#include <xio/version.h>
#include <xio/wait_traits.h>
#include <xio/windows/basic_object_handle.h>
#include <xio/windows/basic_overlapped_handle.h>
#include <xio/windows/basic_random_access_handle.h>
#include <xio/windows/basic_stream_handle.h>
#include <xio/windows/object_handle.h>
#include <xio/windows/overlapped_handle.h>
#include <xio/windows/overlapped_ptr.h>
#include <xio/windows/random_access_handle.h>
#include <xio/windows/stream_handle.h>
#include <xio/writable_pipe.h>
#include <xio/write.h>
#include <xio/write_at.h>

#endif // ASIO_HPP
