name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    uses: kumose/kmpkgcore/.github/workflows/ci-template.yml@master
    with:
      config-command: |
        cmake --preset=default -DKMCMAKE_BUILD_TEST=ON
      build-command: |
        cmake --build build -j$(nproc)
      test-command: |
        ctest --test-dir build --output-on-failure -j1
      deps-ubuntu: libssl-dev
      deps-alpine: openssl-dev
      deps-centos: openssl-devel
      deps-windows: openssl
